name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build
        run: ./deploy.sh build

      - name: Run
        run: ./deploy.sh run
        env:
          DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}

      - name: Clean
        run: ./deploy.sh clean
